#!/usr/bin/env node

var readline = require("readline"),
    vm = require("vm"),
    expression = require("./expression"),
    output = require("./output");

if (process.argv.length < 3) {
  process.argv[2] = "d";
} else if (process.argv.length > 3) {
  console.error("usage: ndjson-split <expression>");
  process.exit(1);
}

var i = -1,
    sandbox = {d: undefined, i: i},
    map = expression(process.argv[2]),
    context = new vm.createContext(sandbox);

readline.createInterface({
  input: process.stdin,
  output: null
}).on("line", function(line) {
  sandbox.i = ++i;
  try {
    sandbox.d = JSON.parse(line);
  } catch (error) {
    console.error("stdin:" + (i + 1));
    console.error(line);
    console.error("^");
    console.error("SyntaxError: " + error.message);
    process.exit(1);
  }
  var rows = map.runInContext(context);
  if (!Array.isArray(rows)) {
    console.error("stdin:" + (i + 1));
    console.error(rows == null ? "null" : JSON.stringify(rows));
    console.error("^");
    console.error("TypeError: not array");
    process.exit(1);
  }
  Array.prototype.forEach.call(rows, output);
});
