#!/usr/bin/env node

var readline = require("readline"),
    vm = require("vm"),
    commander = require("commander"),
    external = require("./external"),
    expression = require("./expression"),
    output = require("./output");

commander
    .version(require("./package.json").version)
    .usage("[options] [expression]")
    .option("-r, --require <module:symbol>", "require an external module", external)
    .parse(process.argv);

if (commander.args.length < 1) {
  commander.args[0] = "d";
} else if (commander.args.length > 1) {
  commander.outputHelp();
  process.exit(1);
}

var i = -1,
    sandbox = commander.require,
    map = expression(commander.args[0]),
    context = new vm.createContext(sandbox);

readline.createInterface({
  input: process.stdin,
  output: null
}).on("line", function(line) {
  sandbox.i = ++i;
  try {
    sandbox.d = JSON.parse(line);
  } catch (error) {
    console.error("stdin:" + (i + 1));
    console.error(line);
    console.error("^");
    console.error("SyntaxError: " + error.message);
    process.exit(1);
  }
  output(map.runInContext(context));
});
