#!/usr/bin/env node

var readline = require("readline"),
    vm = require("vm"),
    expression = require("./expression"),
    output = require("./output");

if (process.argv.length < 3) {
  process.argv[2] = "true";
} else if (process.argv.length > 3) {
  console.error("usage: ndjson-filter [expression]");
  process.exit(1);
}

var i = -1,
    sandbox = {d: undefined, i: i},
    filter = expression(process.argv[2]),
    context = new vm.createContext(sandbox);

readline.createInterface({
  input: process.stdin,
  output: null
}).on("line", function(line) {
  sandbox.i = ++i;
  try {
    sandbox.d = JSON.parse(line);
  } catch (error) {
    console.error("stdin:" + (i + 1));
    console.error(line);
    console.error("^");
    console.error("SyntaxError: " + error.message);
    process.exit(1);
  }
  if (filter.runInContext(context)) {
    output(sandbox.d);
  }
});
