#!/usr/bin/env node

var readline = require("readline"),
    vm = require("vm"),
    expression = require("./expression"),
    output = require("./output");

if (process.argv.length < 3) {
  process.argv[2] = "p.push(d), p";
  process.argv[3] = "[]";
} else if (process.argv.length > 4) {
  console.error("usage: ndjson-reduce [expression [initial]]");
  process.exit(1);
}

var i = -1,
    unset = process.argv.length < 4,
    sandbox = {p: unset ? undefined : expression(process.argv[3], "initial").runInNewContext(), d: undefined, i: i},
    reduce = expression(process.argv[2]),
    context = new vm.createContext(sandbox);

readline.createInterface({
  input: process.stdin,
  output: null
}).on("line", function(line) {
  sandbox.i = ++i;
  try {
    sandbox.d = JSON.parse(line);
  } catch (error) {
    console.error("stdin:" + (i + 1));
    console.error(line);
    console.error("^");
    console.error("SyntaxError: " + error.message);
    process.exit(1);
  }
  sandbox.p = unset ? (unset = false, sandbox.d) : reduce.runInContext(context);
}).on("close", function() {
  output(sandbox.p);
});
