#!/usr/bin/env node

var readline = require("readline"),
    vm = require("vm"),
    commander = require("commander"),
    requires = require("./requires"),
    expression = require("./expression"),
    output = require("./output");

commander
    .version(require("./package.json").version)
    .usage("[options] [expression]")
    .description("Transform values in a newline-delimited JSON stream using a JavaScript expression where \"d\" is the value being transformed.\n\n" +
                 // "  Example: ndjson-map --require crypto=crypto 'd.hash = crypto.createHmac('\"sha256\", \"SECRET\").update(d.message).digest(\"hex\"), d' < file.json")
                 "  Example: ndjson-map --require fs=fs 'd.filesize = fs.statSync(d.filename).size, d'")
    .option("-r, --require <name=module>", "require a module", requires, {d: undefined, i: -1})
    .parse(process.argv);

if (commander.args.length > 1) {
  commander.outputHelp();
  process.exit(1);
}

if (commander.args.length < 1) {
  commander.args[0] = "d";
}

var i = -1,
    sandbox = commander.require,
    map = expression(commander.args[0]),
    context = new vm.createContext(sandbox);

readline.createInterface({
  input: process.stdin,
  output: null
}).on("line", function(line) {
  sandbox.i = ++i;
  try {
    sandbox.d = JSON.parse(line);
  } catch (error) {
    console.error("stdin:" + (i + 1));
    console.error(line);
    console.error("^");
    console.error("SyntaxError: " + error.message);
    process.exit(1);
  }
  output(map.runInContext(context));
});
