#!/usr/bin/env node

var readline = require("readline"),
    vm = require("vm");

var i = -1,
    unset = process.argv.length < 4,
    sandbox = {p: unset ? undefined : vm.runInNewContext(process.argv[3]), d: undefined, i: i},
    reduce = new vm.Script(process.argv[2]),
    context = new vm.createContext(sandbox);

readline.createInterface({
  input: process.stdin,
  output: null
}).on("line", function(line) {
  sandbox.i = ++i;
  try {
    sandbox.d = JSON.parse(line);
  } catch (error) {
    console.error("stdin:" + (i + 1));
    console.error("    " + line);
    console.error("    ^");
    console.error(error.stack);
    process.exit(1);
  }
  sandbox.p = unset ? (unset = false, sandbox.d) : reduce.runInContext(context);
}).on("close", function() {
  console.log(JSON.stringify(sandbox.p));
});
